// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFgFIxiFgvLqJTo-P89RE_pr07vYALMY',
    appId: '1:449159947453:web:378b502200250e304ac3d4',
    messagingSenderId: '449159947453',
    projectId: 'gymproject-13661',
    authDomain: 'gymproject-13661.firebaseapp.com',
    storageBucket: 'gymproject-13661.firebasestorage.app',
    measurementId: 'G-YCQX5NENH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14xkzLbo4ioQ8_vOkOiwm-Ujt71th_T4',
    appId: '1:449159947453:android:deb2bc4c16d072434ac3d4',
    messagingSenderId: '449159947453',
    projectId: 'gymproject-13661',
    storageBucket: 'gymproject-13661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATjaWfPlUTiw98GkQH5B5CwfTwbtkJ-fg',
    appId: '1:449159947453:ios:d99b5957eccf92b94ac3d4',
    messagingSenderId: '449159947453',
    projectId: 'gymproject-13661',
    storageBucket: 'gymproject-13661.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATjaWfPlUTiw98GkQH5B5CwfTwbtkJ-fg',
    appId: '1:449159947453:ios:d99b5957eccf92b94ac3d4',
    messagingSenderId: '449159947453',
    projectId: 'gymproject-13661',
    storageBucket: 'gymproject-13661.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQFgFIxiFgvLqJTo-P89RE_pr07vYALMY',
    appId: '1:449159947453:web:17c535d3097581ce4ac3d4',
    messagingSenderId: '449159947453',
    projectId: 'gymproject-13661',
    authDomain: 'gymproject-13661.firebaseapp.com',
    storageBucket: 'gymproject-13661.firebasestorage.app',
    measurementId: 'G-WHS5EKTJL9',
  );
}
